ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
app_name="cart"
urlpatterns = [
path('addtocart/<n>',views.addtocart,name="addtocart"),
path('cartview',views.cartview,name="cartview"),
path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
path('full_remove/<n>',views.full_remove,name="full_remove"),
path('orderform',views.orderform,name="orderform"),
path('orderview',views.orderview,name="orderview")
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from shop import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name="search"
urlpatterns = [
    path('',views.search,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views

app_name='shop'
urlpatterns = [

    path('',views.allcategories,name='allcat'),
    path('allprod/<p>',views.allproducts,name="allprod"),
    path('detail/<p>',views.detail,name="detail"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Products
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    ordered_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.IntegerField(null=True)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    def __str__(self):
        return self.product.name

class Account(models.Model):
    acctnum=models.IntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=30)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/category",null=True,blank=True)
    def __str__(self):
        return self.name

class Products(models.Model):
    name=models.CharField(max_length=30)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/product",null=True,blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Products
from cart.models import Cart,Account,Order
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
@login_required
def cartview(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total+=i.quantity*i.product.price
    return render(request,'cartview.html',{'c':cart,'total':total})
@login_required
def addtocart(request,n):
    p=Products.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.product.stock > 0):
            cart.quantity+=1
            cart.save()
            p.stock-=1
            p.save()
    except:
        if(p.stock>0):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()
    return cartview(request)
@login_required
def cart_remove(request,n):
    p=Products.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
            p.stock+=1
            p.save()
        else:
            cart.delete()
    except:
        pass
    return cartview(request)
@login_required
def full_remove(request,n):
    p = Products.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)

        cart.delete()
    except:
        pass
    return cartview(request)
@login_required
def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)
        print(n,cart)
        total = 0
        for i in cart:
            total += i.quantity * i.product.price
        try:
            num=int(n)
            test = Account.objects.get(accttype='savings')
            print(test)
            print('num',num, n)
            ac=Account.objects.get(acctnum=n)

            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="Your order placed successfully"
                print('hello after loop')
                return render(request,'orderdetails.html',{'msg':msg})
            else:
                msg="Insufficient amount. You cant place order"
                return render(request, 'orderdetails.html', {'msg': msg})
        except Exception as e:
            print(e)
    return render(request,'orderform.html')
@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)

    return render(request,"orderview.html",{'o':o})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Products
from django.db.models import Q
def search(request):
    q=""
    products=None
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            products=Products.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request,'search.html',{'query':query,'p':products})

ecommerce/shop/views.py
from django.db.models import Q
from django.shortcuts import render
from shop.models import Category, Products
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

def allcategories(request):
    c = Category.objects.all()
    return render(request, 'category.html', {'c': c})


def allproducts(request, p):
    c = Category.objects.get(name=p)
    p = Products.objects.filter(category=c)
    return render(request, 'product.html', {'c': c, 'p': p})

def detail(request, p):
    p=Products.objects.get(name=p)
    return render(request,'detail.html',{'p':p})

def register(request):
    if (request.method=="POST"):
        u = request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        fn = request.POST['f']
        ln = request.POST['l']
        e = request.POST['e']

        if(p==cp):
            user=User.objects.create_user(username=u,password=p,first_name=fn,last_name=ln,email=e)
            user.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("Passwords are not same")
    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            return HttpResponse("Invalid credentials")

    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return redirect('shop:login')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/b1519738a2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

    <div class="container-fluid text-center">
        <img src="{% static 'images/logo.jpg' %}" height="150px" width="150px">
    </div>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All categories
          </a>
          <ul class="dropdown-menu">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>

          {% if user.is_authenticated %}

          <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% if user.is_superuser == False %}

           <li class="nav-item">
          <a class="nav-link active" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sub>{{count}}</sub></i></a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
          {% endif %}
          {% else %}
          <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}

      </ul>
        <form class="d-flex" role="search" method="POST" action="{% url 'search:search' %}">
            {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<footer>
    <div class="footer">
        <p>&#169; My shop pvt ltd.All Rights Reserved.</p>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        <h4 class="text-center">Shopping cart</h4>
        <div class="col-6">
            <table class="table table-bordered text-center fs-5">
                <tr>
                    <th colspan="5" class="text-center">Cart Items</th>
                </tr>
                {% for i in c %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="100px"></td>
                    <td>
                        <b>{{i.product.name}}</b>
                    </td>
                    <td><b>ProductID:{{i.product.name}}</b><br>
                        <b>Unit Price:{{i.product.price}}</b><br>
                        <b>Quantity:{{i.quantity}}*{{i.product.price}}</b><br><br>
                    </td>
                    <td><b>Subtotal:{{i.subtotal}}</b></td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-danger"></i></a>
                        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-danger"></i></a>
                    {% else %}
                        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-danger"></i></a>
                    {% endif %}
                    </td>

                </tr>
                {% endfor %}
            </table>
        </div>

        <div class="container col-4 ms-5">
            <table class="table table-bordered">
                <tr>
                    <th colspan="5">Check Out</th>
                </tr>
                <tr>
                    <th>Total:<span style="position:absolute;right:20px;">{{total}}</span></th>
                </tr>
            </table>
            <a href="{% url 'cart:orderform' %}" class="btn btn-danger">Place Order</a>
            <a href="{% url 'shop:allcat' %}" class="btn btn-danger">Continue Shopping</a>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <img src="{% static 'images/banner2.jpeg' %}" height="500px" width="100%">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px">
    <h2 class="fw-bold" style="text-align:center ">Our Collections</h2>
    <p style="text-align:justify;line-height:2 ">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>

<div class="container-fluid mt=3" style="margin-bottom:100px">
    <div class="row">
        {% for i in c %}
        <div class="col-sm- 4">
        <div class="card text-center" style="width: 28rem;">
            <img src="{{i.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <a href="{% url 'shop:allprod' i.name %}" class="btn btn-primary" >Products</a>
            </div>
        </div>

        </div>
         {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <img src="{{p.image.url}}" height="400px" width="400px">
        </div>
        <div class="col-sm-6 me-5">
            <h2 class="mt-5">{{p.name}}</h2>
            <p class="h5 mt-5 lh-base" style="text-align:justify;">{{p.desc}}</p>
            <h4 class="mt-5">{{p.price}}</h4>
            {{p.stock}}
            {% if user.is_superuser == True %}
                {% if p.stock == 0 %}
                    <h2>Out of stock</h2>
                    <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">Add stock</a>
                {% else %}
                <h2>Product in stock</h2>
                <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">Add stock</a>
                {% endif %}
            {% else %}
                {% if p.stock == 0 %}
                    <h2>Out of stock</h2>
                {% else %}
                    <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger mt-5">Add to cart</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2 class="mt-5">Login</h2>
       <form class="form container" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>
<div>
    <input type="submit" class="form-control">
</div>
   </form>
</center>
{% endblock %}

ecommerce/templates/orderdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h4 class="text-center text-success">{{msg}}</h4>
    <h4 class="text-center text-danger">Thank You..</h4>
    <h4 class="text-center"><a href="{% url 'shop:allcat' %}">Continue shopping</a> </h4>
</div>

{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="text-center">Order Form</h3>
  <form class="form container-fluid mb-5" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the address">
</div>
<div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="number" class="form-control" name="p" placeholder="Enter the phone">
</div>
<div class="mb-3">
  <label class="form-label">Account number</label>
  <input type="number" class="form-control" name="n" placeholder="Enter the account number">
</div>

  <div class="mt-4">
    <input type="submit" class="form-control">
  </div>
</form>
</center>

{% endblock %}

ecommerce/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <h4>Name of customer:{{u}}</h4>
        {% for i in o %}

        <div class="col-sm-4 mb-3">
            <img src="{{i.product.image.url}}" height="200px" width="200px">
        </div>
        <div class="col-sm-6 me-5 mb-3 text-center border border-1">
            <b>Product name:{{i.product.name}}</b><br>
            <b>Product price:{{i.product.price}}</b><br>
            <b>Delivery address:{{i.address}}</b><br>
            <b>Customer phone:{{i.phone}}</b><br>
            <b>Ordered on:{{i.ordered_date}}</b><br>
            <b>Delivery satus:{{i.delivery_status}}</b><br>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <img src="{{c.image.url}}" height="500px" width="100%">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px">
    <h2 class="fw-bold" style="text-align:center ">{{c.name}}</h2>
    <p style="text-align:justify;line-height:2 ">{{c.desc}}</p>
</div>

<div class="container-fluid mt=3" style="margin-bottom:100px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
        <div class="card text-center" style="width: 28rem;">
            <img src="{{i.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" >Details</a>
            </div>
        </div>

        </div>
         {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2 class="mt-5">Register here</h2>
    <form class="form container-fluid mb-5" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>
<div class="mb-3">
  <label class="form-label">Confirm password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter the password">
</div>
  <div class="mb-3">
  <label class="form-label">First name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter the firstname">
</div>
  <div class="mb-3">
  <label class="form-label">Last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the lastname">
</div>
        <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter the email">
</div>

  <div class="mt-4">
    <input type="submit" class="form-control">
  </div>
</form>
</center>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <center>
        <h5>You have searched for {{query}}</h5>
        {% if p %}
        <div class="container-fluid mt=3" style="margin-bottom:100px">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-3" style="margin-right:10px;margin-bottom:20px;">

        <div class="card text-center" style="width: 18rem;">
            <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">{{i.name}}</h5>
                <h6 class="card-title text-center">{{i.price}}</h6>
                <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" >Details</a>
            </div>
        </div>

        </div>
         {% endfor %}
    </div>
</div>
        {% else %}
        <h6 class="text-center">No Results Found</h6>
        {% endif %}
    </center>
</div>
{% endblock %}